"""pesan perubahan

Revision ID: 0502af6c8b81
Revises: e4ace5b9da7b
Create Date: 2026-05-26 16:33:47.602313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0502af6c8b81'
down_revision: Union[str, None] = 'e4ace5b9da7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
