"""tambah is_recieve_by_branch ke purchases

Revision ID: 86094115e09e
Revises: 
Create Date: 2026-05-17 19:33:20.627366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86094115e09e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'loyalty_points')
    op.add_column('purchases', sa.Column('is_received_by_branch', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'is_received_by_branch')
    op.add_column('customers', sa.Column('loyalty_points', sa.REAL(), server_default=sa.text('0'), nullable=True))
    # ### end Alembic commands ###
