"""add_tax_columns_to_returns_and_sales

Revision ID: 9419282e6bd5
Revises: 86094115e09e
Create Date: 2026-05-21 15:22:11.472933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9419282e6bd5'
down_revision: Union[str, None] = '86094115e09e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_returns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_tax_included', sa.Boolean(), nullable=True))

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_tax_included', sa.Boolean(), nullable=True))

    with op.batch_alter_table('sale_returns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_tax_included', sa.Boolean(), nullable=True))

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_percent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_tax_included', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'is_tax_included')
    op.drop_column('sales', 'tax_percent')
    op.drop_column('sale_returns', 'is_tax_included')
    op.drop_column('sale_returns', 'tax_percent')
    op.drop_column('purchases', 'is_tax_included')
    op.drop_column('purchases', 'tax_percent')
    op.drop_column('purchase_returns', 'is_tax_included')
    op.drop_column('purchase_returns', 'tax_percent')
    op.drop_constraint(None, 'items', type_='unique')
    op.create_index(op.f('ix_items_name_unique'), 'items', ['name'], unique=1)
    op.add_column('customers', sa.Column('loyalty_points', sa.REAL(), server_default=sa.text('0'), nullable=True))
    # ### end Alembic commands ###
