"""fix trade_ins branch_id

Revision ID: a5c0722bfbbc
Revises: 0502af6c8b81
Create Date: 2026-05-26 20:16:44.219667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5c0722bfbbc'
down_revision: Union[str, None] = '0502af6c8b81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_ins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_trade_ins_branch', 'branches', ['branch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_ins', schema=None) as batch_op:
        batch_op.drop_constraint('fk_trade_ins_branch', type_='foreignkey')
        batch_op.drop_column('branch_id')
    # ### end Alembic commands ###
