"""add deposit_balance to customer and supplier

Revision ID: e4ace5b9da7b
Revises: 9419282e6bd5
Create Date: 2026-05-26 16:32:05.157140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4ace5b9da7b'
down_revision: Union[str, None] = '9419282e6bd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('deposit_balance', sa.Float(), nullable=True))
    op.add_column('suppliers', sa.Column('deposit_balance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'deposit_balance')
    op.drop_column('customers', 'deposit_balance')
    # ### end Alembic commands ###
